#!/usr/bin/env python3
"""Generate src/secrets.h from local.env (shell KEY=value format)."""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = ROOT / "local.env"
OUT_PATH = ROOT / "src" / "secrets.h"


def load_env(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:].strip()
        m = re.match(r"([A-Za-z_][A-Za-z0-9_]*)=(.*)$", line)
        if not m:
            continue
        key, val = m.group(1), m.group(2).strip()
        if (val.startswith('"') and val.endswith('"')) or (val.startswith("'") and val.endswith("'")):
            val = val[1:-1]
        out[key] = val
    return out


def c_define_string(name: str, value: str) -> str:
    return f"#define {name} {json.dumps(value)}"


def main() -> None:
    if not ENV_PATH.is_file():
        print(f"Missing {ENV_PATH}. Run: make -C .. setup  (from repo root: make setup)", file=sys.stderr)
        sys.exit(1)

    env = load_env(ENV_PATH)
    for key in ("WIFI_SSID", "WIFI_PSK", "BRAIN_IP"):
        if key not in env or not env[key].strip():
            print(f"Set {key} in {ENV_PATH}", file=sys.stderr)
            sys.exit(1)

    port = env.get("BRAIN_PORT", "8080").strip() or "8080"
    if not port.isdigit():
        print("BRAIN_PORT must be a number if set", file=sys.stderr)
        sys.exit(1)

    lines = [
        "/* Generated by scripts/gen-secrets.py — do not edit. */",
        "#pragma once",
        "",
        c_define_string("WORMS_WIFI_SSID", env["WIFI_SSID"]),
        c_define_string("WORMS_WIFI_PSK", env["WIFI_PSK"]),
        c_define_string("WORMS_BRAIN_IP", env["BRAIN_IP"]),
        f"#define WORMS_BRAIN_PORT {int(port)}",
        "",
    ]
    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
